tap "homebrew/bundle"
tap "homebrew/services"
tap "sue/local-cask"
brew "bat"
brew "bitwarden-cli"
brew "chezmoi"
brew "curl"
brew "displayplacer"
brew "fd"
brew "fpp"
brew "fzf"
brew "gh"
brew "ghq"
brew "git"
brew "mas"
brew "mise"
brew "neofetch"
brew "neovim"
brew "ripgrep"
brew "tmux"
brew "tree"
brew "urlscan"
brew "yt-dlp"
brew "zimfw"
brew "zoxide"
cask "ableton-live-lite"
cask "adobe-digital-editions"
cask "alacritty"
cask "alfred"
cask "android-file-transfer"
cask "android-platform-tools"
cask "android-studio"
cask "anki"
cask "beeper"
cask "bitwarden"
cask "chatgpt"
cask "chatgpt-atlas"
cask "codex"
cask "codex-app"
cask "copilot-cli"
cask "cursor"
cask "deepl"
cask "discord"
cask "docker-desktop"
cask "duet"
cask "epic-games"
cask "font-hackgen"
cask "gimp"
cask "google-chrome"
cask "google-japanese-ime"
cask "helpwire-operator"
cask "iina"
cask "iriunwebcam"
cask "karabiner-elements"
cask "libreoffice"
cask "localsend"
cask "microsoft-auto-update"
cask "microsoft-teams"
cask "netnewswire"
cask "notion"
cask "obsidian"
cask "protonvpn"
cask "rectangle"
cask "rekordbox"
cask "shottr"
cask "slack"
cask "sue/local-cask/stayfree"
cask "steam"
cask "tidal"
cask "tor-browser"
cask "virtualbox"
cask "visual-studio-code"
cask "wechat"
cask "whatsapp"
cask "wireshark-app"
cask "zoom"
mas "Dictionaries", id: 1380563956
mas "djay Pro", id: 450527929
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "koala", id: 1479881366
mas "LINE", id: 539883307
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Perplexity", id: 6714467650
mas "ScreenZen", id: 1541027222
vscode "anthropic.claude-code"
vscode "asvetliakov.vscode-neovim"
vscode "davidanson.vscode-markdownlint"
vscode "docker.docker"
vscode "eamodio.gitlens"
vscode "foam.foam-vscode"
vscode "github.codespaces"
vscode "github.copilot-chat"
vscode "github.remotehub"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "james-yu.latex-workshop"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode.azure-repos"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-repositories"
vscode "oderwat.indent-rainbow"
vscode "openai.chatgpt"
vscode "pkief.material-icon-theme"
vscode "ritwickdey.liveserver"
vscode "rooveterinaryinc.roo-cline"
vscode "samplavigne.p5-vscode"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "streetsidesoftware.code-spell-checker"
vscode "yzhang.markdown-all-in-one"
